# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/haydn-hotword/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/haydn-hotword/common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/haydn-hotword/common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml

PRODUCT_PACKAGES += \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    com.android.hotwordenrollment.common.util
